#Dockerfile review
# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Review.Web/*.csproj ./Review.Web/
RUN dotnet restore

# copy everything else and build app
COPY Review.Web/. ./Review.Web/
WORKDIR /source/Review.Web
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 8282:80
ENTRYPOINT ["dotnet", "Review.Web.dll"]